import type { AdditionalChildExpensesLegalPath } from "@/data/additional-child-expenses-legal-review";
import { ADDITIONAL_CHILD_EXPENSES_SCENARIOS, type AdditionalChildExpensesField, type AdditionalChildExpensesScenarioKey } from "@/data/additional-child-expenses-route";
export type AdditionalChildExpensesValues = Record<string, string | undefined>;
export type AdditionalChildExpensesIssue = { field: string; message: string };
export type AdditionalChildExpensesDecision = { allowed: boolean; outcomeKey: string; legalPath: AdditionalChildExpensesLegalPath; resultKind: "checklist" | "agreementDraft" | "courtDraft" | "legalReviewOnly"; resultLabel: string; documentTitle: string; filingReady: false; requiresLegalReview: boolean; pdfAvailable: true; issues: AdditionalChildExpensesIssue[]; notices: string[]; preparedData: Array<{ label: string; value: string }>; filingSteps: string[]; draftText: string };

export function validateAdditionalChildExpenses(scenarioKey: AdditionalChildExpensesScenarioKey, values: AdditionalChildExpensesValues): AdditionalChildExpensesDecision {
  const scenario = ADDITIONAL_CHILD_EXPENSES_SCENARIOS[scenarioKey]; const preparedData = scenario.helperFields.filter((field) => values[field.name]?.trim()).map((field) => ({ label: field.label, value: displayValue(field, values[field.name] ?? "") })); const missing = scenario.helperFields.filter((field) => field.required && !values[field.name]?.trim()).map((field) => ({ field: field.name, message: `Заполните поле «${field.label}».` }));
  if (missing.length) return base("missing-data", "assessment", "legalReviewOnly", "Не хватает обязательных сведений", scenario.mainDocument, true, missing, preparedData, ["Документ не формируется без критических данных."], ["Заполните обязательные поля."], "");
  if (values.international !== "no") return review(values.international === "yes" ? "international-review" : "international-unclear", "Нужна проверка международного элемента", "Этот маршрут не определяет применимое право и суд для международной ситуации.", preparedData);
  if (values.childStatus === "adult-other") return review("adult-child-inapplicable", "Статья 86 СК РФ по указанному статусу не подтверждена", "Маршрут охватывает несовершеннолетних и нетрудоспособных совершеннолетних нуждающихся детей.", preparedData);
  if (values.childStatus === "unsure") return review("child-status-unclear", "Статус ребёнка не подтверждён", "Сначала подтвердите возраст, нетрудоспособность и нуждаемость, если ребёнок совершеннолетний.", preparedData);
  if (values.expenseCategory === "ordinary") return review("ordinary-expense-review", "Обычные расходы не признаны дополнительными", "Повседневные траты не относятся к статье 86 СК РФ автоматически. Проверьте обычный алиментный маршрут.", preparedData);
  if (values.expenseCategory === "other") return review("exceptional-circumstance-unclear", "Исключительное обстоятельство требует проверки", "Открытый перечень статьи 86 СК РФ не позволяет автоматически квалифицировать указанное обстоятельство.", preparedData);
  if (values.necessityEvidence !== "yes") return review(values.necessityEvidence === "no" ? "necessity-not-supported" : "necessity-unclear", "Необходимость расходов не подтверждена", "Для договорного или судебного результата нужны подтверждения необходимости и размера расходов.", preparedData);
  if (scenarioKey === "assessment") return base(`${values.childStatus}-${values.expenseCategory}-eligible-checklist`, "assessment", "checklist", "ЧЕК-ЛИСТ ПРИМЕНИМОСТИ", "Проверка дополнительных расходов на ребёнка", true, [], preparedData, ["Признаки статьи 86 СК РФ предварительно выявлены, но окончательную оценку даёт суд либо нотариус при согласовании условий."], ["Соберите оригиналы подтверждений необходимости и суммы.", "Определите, согласен ли второй родитель.", "При согласии обсудите нотариальное соглашение; при споре проверьте судебный путь."], "");
  if (scenarioKey === "agreement") {
    if (values.parentsAgree !== "yes") return review(values.parentsAgree === "no" ? "agreement-not-reached" : "agreement-unclear", "Согласие родителей не подтверждено", "Для добровольного проекта нужно согласие обоих родителей; при споре оцените судебный путь.", preparedData);
    const title = "Проект условий соглашения об участии в дополнительных расходах на ребёнка";
    return base(`${values.expenseCategory}-agreement-draft`, "agreement", "agreementDraft", "ПРОЕКТ УСЛОВИЙ — ДЛЯ НОТАРИУСА", title, true, [], preparedData, ["Проект не заменяет нотариально удостоверенное соглашение и не имеет силы исполнительного листа."], ["Сверьте документы и расчёт.", "Передайте проект выбранному нотариусу.", "Уточните тариф и перечень оригиналов.", "Подписывайте только окончательный текст после проверки нотариусом."], buildDraft(values, title));
  }
  if (!isPositiveAmount(values.totalAmount)) return review("amount-not-confirmed", "Сумма расходов не подтверждена", "Укажите положительную сумму и приложите её расчёт; помощник не проверяет арифметику по отдельным документам.", preparedData);
  if (values.courtConfirmed !== "yes" || !isOfficialCourtSource(values.courtSource)) return review("court-not-confirmed", "Суд не подтверждён", "Проверьте суд и территориальную подсудность на официальном ресурсе судебной системы.", preparedData, "court");
  const incurred = scenarioKey === "incurred"; const title = incurred ? "Черновик требования о взыскании понесённых дополнительных расходов на ребёнка" : "Черновик требования об участии в будущих дополнительных расходах на ребёнка";
  return base(`${values.expenseCategory}-${incurred ? "incurred" : "future"}-court-draft`, "court", "courtDraft", "ЧЕРНОВИК — НЕ ГОТОВ К ПОДАЧЕ", title, true, [], preparedData, ["Исключительный характер, необходимость, сумма, состав требования и подсудность требуют юридической проверки."], ["Сверьте назначение и расчёт каждого расхода.", "Проверьте материальное и семейное положение сторон.", "Подтвердите суд и состав участников.", "Проверьте черновик у юриста до подачи."], buildDraft(values, title, values.courtName));
}
function displayValue(field: AdditionalChildExpensesField, value: string) { return field.options?.find((option) => option.value === value)?.label ?? value; }
function isPositiveAmount(value?: string) { const amount = Number(String(value ?? "").replace(",", ".")); return Number.isFinite(amount) && amount > 0; }
function isOfficialCourtSource(value?: string) { try { const host = new URL(value ?? "").hostname.toLowerCase(); return host === "sudrf.ru" || host.endsWith(".sudrf.ru") || host === "mos-gorsud.ru" || host.endsWith(".mos-gorsud.ru"); } catch { return false; } }
function review(outcomeKey: string, title: string, notice: string, preparedData: AdditionalChildExpensesDecision["preparedData"], legalPath: AdditionalChildExpensesLegalPath = "assessment") { return base(outcomeKey, legalPath, "legalReviewOnly", "Требуется юридическая проверка", title, true, [], preparedData, [notice], [notice, "Не используйте результат как готовый документ."], ""); }
function base(outcomeKey: string, legalPath: AdditionalChildExpensesLegalPath, resultKind: AdditionalChildExpensesDecision["resultKind"], resultLabel: string, documentTitle: string, requiresLegalReview: boolean, issues: AdditionalChildExpensesIssue[], preparedData: AdditionalChildExpensesDecision["preparedData"], notices: string[], filingSteps: string[], draftText: string): AdditionalChildExpensesDecision { return { allowed: issues.length === 0 && resultKind !== "legalReviewOnly", outcomeKey, legalPath, resultKind, resultLabel, documentTitle, filingReady: false, requiresLegalReview, pdfAvailable: true, issues, notices, preparedData, filingSteps, draftText }; }
function buildDraft(values: AdditionalChildExpensesValues, title: string, addressee?: string) { return ["ЧЕРНОВИК — НЕ ГОТОВ К ПОДАЧЕ", "ТРЕБУЕТСЯ ЮРИДИЧЕСКАЯ И АРИФМЕТИЧЕСКАЯ ПРОВЕРКА", addressee ? `\nВ ${addressee}` : "", "", title.toUpperCase(), "", `Заявитель: ${values.applicantData ?? ""}`, `Другой родитель: ${values.otherParentData ?? ""}`, `Ребёнок: ${values.childData ?? ""}`, `Обстоятельства: ${values.expenseDetails ?? ""}`, `Подтверждения: ${values.evidenceDetails ?? ""}`, `Общая сумма: ${values.totalAmount ?? ""} руб.`, `Предлагаемое участие: ${values.requestedShare ?? ""}`, `Материальные и семейные обстоятельства: ${values.financialCircumstances ?? ""}`, values.paymentProof ? `Оплата подтверждается: ${values.paymentProof}` : "", values.futureCalculation ? `Будущие расходы: ${values.futureCalculation}` : "", values.paymentTerms ? `Согласованные условия: ${values.paymentTerms}` : "", "", "Точный способ защиты, расчёт, просительная часть и приложения подлежат проверке."].filter(Boolean).join("\n"); }
