import { RUSSIAN_REGIONS } from "@/data/guardianship-territories";
import type { AdoptionLegalPath } from "@/data/adoption-legal-review";
import { ADOPTION_SCENARIOS, type AdoptionField, type AdoptionScenarioKey } from "@/data/adoption-route";
export type AdoptionValues = Record<string, string | undefined>;
export type AdoptionIssue = { field: string; message: string };
export type AdoptionDecision = { allowed: boolean; outcomeKey: string; legalPath: AdoptionLegalPath; resultKind: "checklist" | "legalReviewOnly"; resultLabel: string; documentTitle: string; filingReady: false; requiresLegalReview: boolean; pdfAvailable: true; issues: AdoptionIssue[]; notices: string[]; preparedData: Array<{ label: string; value: string }>; filingSteps: string[]; draftText: "" };
export function getVisibleAdoptionFields(scenarioKey: AdoptionScenarioKey, values: AdoptionValues) { return ADOPTION_SCENARIOS[scenarioKey].helperFields.filter((field) => field.name !== "childConsent" || values.childAge === "10-plus"); }
export function validateAdoption(scenarioKey: AdoptionScenarioKey, values: AdoptionValues): AdoptionDecision {
  const scenario = ADOPTION_SCENARIOS[scenarioKey]; const fields = getVisibleAdoptionFields(scenarioKey, values); const preparedData = fields.filter((field) => values[field.name]?.trim()).map((field) => ({ label: field.label, value: displayValue(field, values[field.name] ?? "") }));
  const missing = fields.filter((field) => field.required && !values[field.name]?.trim()).map((field) => ({ field: field.name, message: `Заполните поле «${field.label}».` }));
  if (missing.length) return base("missing-data", "assessment", "legalReviewOnly", "Не хватает обязательных сведений", scenario.mainDocument, missing, preparedData, ["Заполните обязательные поля."], [], true);
  if (values.region && !RUSSIAN_REGIONS.some((region) => region.id === values.region)) return base("invalid-region", "assessment", "legalReviewOnly", "Регион не подтверждён", scenario.mainDocument, [{ field: "region", message: "Выберите регион из справочника." }], preparedData, ["Произвольное название региона не используется в результате."], [], true);
  if (scenarioKey === "international") return review("international-legal-review", scenario.mainDocument, "Иностранный элемент требует проверки гражданства, места проживания, международного договора, ограничений и компетентного суда.", preparedData, "international");
  if (values.childAge === "unsure") return review("child-age-unclear", "Нужно уточнить возраст ребёнка", "Возраст влияет на требование согласия ребёнка.", preparedData, "assessment");
  if (values.childAge === "10-plus" && values.childConsent !== "yes") return review(values.childConsent === "no" ? "child-no-consent" : "child-consent-review", "Согласие ребёнка не подтверждено", "Правило и возможное исключение статьи 132 СК РФ должен проверить суд; чек-лист готовности не формируется.", preparedData, "consent");
  if (values.eligibilityChecked !== "yes") return review("candidate-eligibility-review", "Ограничения кандидата не проверены", "До дальнейшего движения проверьте весь перечень статьи 127 СК РФ и подтверждающие документы.", preparedData, "assessment");
  if (scenarioKey === "step-parent") {
    if (values.marriedToParent !== "yes") return review("step-parent-status-review", "Статус отчима или мачехи не подтверждён", "Этот сценарий предназначен для супруга родителя; выберите общий маршрут или получите правовую проверку.", preparedData, "assessment");
    if (values.otherParentConsent !== "yes" || values.applicantSpouseConsent !== "yes") return review("step-parent-consent-review", "Не все согласия подтверждены", "Наличие исключения из требования согласия устанавливается только после проверки документов и обстоятельств.", preparedData, "consent");
  }
  if (scenarioKey === "domestic") {
    if (values.russianResident !== "yes") return review("foreign-element-detected", "Обнаружен иностранный элемент", "Перейдите в международный маршрут; российский чек-лист не применяется автоматически.", preparedData, "international");
    if (values.childStatusConfirmed !== "yes") return review("child-status-review", "Статус ребёнка не подтверждён", "Орган опеки должен подтвердить правовой статус и допустимый порядок устройства ребёнка.", preparedData, "assessment");
  }
  if (scenarioKey === "consent-review") return review("consent-exception-review", scenario.mainDocument, values.claimedException === "other" ? "Основание не относится к подтверждённому перечню; требуется индивидуальная проверка." : "Даже указанное основание статьи 130 СК РФ требует доказательств и судебной оценки.", preparedData, "consent");
  const needsConclusion = scenarioKey === "domestic" && values.candidateConclusion !== "yes";
  return base(`${scenarioKey}-${needsConclusion ? "prepare-conclusion" : "checklist"}`, "domestic", "checklist", "Персональный чек-лист — НЕ ЯВЛЯЕТСЯ ЗАЯВЛЕНИЕМ", scenario.mainDocument, [], preparedData, needsConclusion ? ["Сначала получите заключение о возможности быть усыновителем.", "Конкретный орган опеки не подтверждён одним выбором региона."] : ["Чек-лист помогает проверить комплект, но не подтверждает готовность заявления в суд.", "Конкретный орган опеки и суд проверьте по официальным территориальным источникам."], scenario.steps, true);
}
function displayValue(field: AdoptionField, value: string) { if (field.name === "region") return RUSSIAN_REGIONS.find((region) => region.id === value)?.label ?? value; return field.options?.find((option) => option.value === value)?.label ?? value; }
function review(outcomeKey: string, title: string, notice: string, preparedData: AdoptionDecision["preparedData"], path: AdoptionLegalPath) { return base(outcomeKey, path, "legalReviewOnly", "Требуется юридическая проверка", title, [], preparedData, [notice], [notice, "Не формируйте и не подавайте заявление до проверки статусов, согласий и компетентного органа."], true); }
function base(outcomeKey: string, legalPath: AdoptionLegalPath, resultKind: AdoptionDecision["resultKind"], resultLabel: string, documentTitle: string, issues: AdoptionIssue[], preparedData: AdoptionDecision["preparedData"], notices: string[], filingSteps: string[], requiresLegalReview: boolean): AdoptionDecision { return { allowed: issues.length === 0 && resultKind !== "legalReviewOnly", outcomeKey, legalPath, resultKind, resultLabel, documentTitle, filingReady: false, requiresLegalReview, pdfAvailable: true, issues, notices, preparedData, filingSteps, draftText: "" }; }
