import type { ChildNameLegalPath } from "@/data/child-name-legal-review";
import { CHILD_NAME_SCENARIOS, type ChildNameField, type ChildNameScenarioKey } from "@/data/child-name-route";
export type ChildNameValues = Record<string, string | undefined>;
export type ChildNameIssue = { field: string; message: string };
export type ChildNameDecision = { allowed: boolean; outcomeKey: string; legalPath: ChildNameLegalPath; resultKind: "checklist" | "dataSheet" | "legalReviewOnly"; resultLabel: string; documentTitle: string; filingReady: false; requiresLegalReview: boolean; pdfAvailable: true; issues: ChildNameIssue[]; notices: string[]; preparedData: Array<{ label: string; value: string }>; filingSteps: string[]; draftText: "" };
export function getVisibleChildNameFields(scenarioKey: ChildNameScenarioKey, values: ChildNameValues) { return CHILD_NAME_SCENARIOS[scenarioKey].helperFields.filter((field) => field.name !== "childConsent" || values.age === "10-13"); }
export function validateChildName(scenarioKey: ChildNameScenarioKey, values: ChildNameValues): ChildNameDecision {
  const scenario = CHILD_NAME_SCENARIOS[scenarioKey]; const fields = getVisibleChildNameFields(scenarioKey, values); const preparedData = fields.filter((field) => values[field.name]?.trim()).map((field) => ({ label: field.label, value: displayValue(field, values[field.name] ?? "") })); const missing = fields.filter((field) => field.required && !values[field.name]?.trim()).map((field) => ({ field: field.name, message: `Заполните поле «${field.label}».` }));
  if (missing.length) return base("missing-data", "assessment", "legalReviewOnly", "Не хватает обязательных сведений", scenario.mainDocument, missing, preparedData, ["Заполните обязательные поля."], [], true);
  if (scenarioKey === "patronymic-special") return review(values.basis === "other" ? "patronymic-basis-unclear" : `patronymic-${values.basis}-review`, scenario.mainDocument, "Порядок изменения отчества зависит от подтверждённого специального основания и актовой записи.", preparedData, "special");
  if (scenarioKey === "fourteen-to-seventeen") {
    if (values.age !== "14-17") return review("age-route-review", "Возраст не соответствует маршруту", "Для совершеннолетнего действует общий маршрут, а неопределённый возраст нужно подтвердить.", preparedData, "assessment");
    if (values.fullCapacity !== "yes" && values.representativeConsent !== "yes") return review(values.representativeConsent === "no" ? "court-consent-required" : "consent-status-review", "Не подтверждено основание для подачи", "При отсутствии необходимых согласий вопрос решается на основании судебного решения, если полная дееспособность не приобретена.", preparedData, "court");
    return base("form-20-data-sheet", "zags", "dataSheet", "Лист данных — НЕ ЯВЛЯЕТСЯ ФОРМОЙ №20", scenario.mainDocument, [], preparedData, ["Перенесите сведения в действующую официальную форму №20 и проверьте комплект в ЗАГС."], scenario.steps, true);
  }
  if (values.element === "patronymic") return review("patronymic-special-basis-required", "Нужно проверить специальное основание", "Статья 59 СК РФ не применяется автоматически к изменению отчества ребёнка до 14 лет.", preparedData, "special");
  if (values.age === "10-13" && values.childConsent !== "yes") return review(values.childConsent === "no" ? "child-no-consent" : "child-consent-unclear", "Согласие ребёнка не подтверждено", "С 10 лет изменение имени или фамилии производится только с согласия ребёнка.", preparedData, "assessment");
  if (scenarioKey === "under-fourteen-agreement") {
    if (values.parentsAgree !== "yes") return review("parents-agreement-review", "Совместная просьба родителей не подтверждена", "Выберите ветку раздельного проживания или проверьте судебный порядок.", preparedData, "assessment");
    return base("guardianship-joint-data-sheet", "guardianship", "dataSheet", "Лист данных — НЕ ЯВЛЯЕТСЯ РЕГИОНАЛЬНЫМ ЗАЯВЛЕНИЕМ", scenario.mainDocument, [], preparedData, ["Компетентный орган и региональная форма подтверждаются отдельно."], scenario.steps, true);
  }
  if (values.element !== "surname") return review("separate-parent-wrong-element", "Эта ветка подтверждена только для фамилии", "Пункт 2 статьи 59 СК РФ регулирует присвоение ребёнку фамилии родителя, с которым он живёт.", preparedData, "assessment");
  if (values.livesWithApplicant !== "yes") return review("residence-status-review", "Проживание ребёнка с заявителем не подтверждено", "Применимость пункта 2 статьи 59 СК РФ требует проверки фактических обстоятельств.", preparedData, "assessment");
  if (values.otherParentPosition === "objects" || values.otherParentPosition === "unsure") return review("other-parent-position-review", scenario.mainDocument, "Возражения или неизвестная позиция второго родителя требуют индивидуальной оценки органом опеки.", preparedData, "guardianship");
  if (values.otherParentPosition === "exception") return review("other-parent-exception-review", scenario.mainDocument, "Неучёт мнения второго родителя допустим только при документально подтверждённом основании из статьи 59 СК РФ.", preparedData, "guardianship");
  return base("separate-parent-checklist", "guardianship", "checklist", "Персональный чек-лист — НЕ ЯВЛЯЕТСЯ РЕШЕНИЕМ ОРГАНА ОПЕКИ", scenario.mainDocument, [], preparedData, ["Орган опеки самостоятельно оценивает интересы ребёнка."], scenario.steps, true);
}
function displayValue(field: ChildNameField, value: string) { return field.options?.find((option) => option.value === value)?.label ?? value; }
function review(outcomeKey: string, title: string, notice: string, preparedData: ChildNameDecision["preparedData"], path: ChildNameLegalPath) { return base(outcomeKey, path, "legalReviewOnly", "Требуется юридическая проверка", title, [], preparedData, [notice], [notice, "Не используйте результат как заявление или разрешение."], true); }
function base(outcomeKey: string, legalPath: ChildNameLegalPath, resultKind: ChildNameDecision["resultKind"], resultLabel: string, documentTitle: string, issues: ChildNameIssue[], preparedData: ChildNameDecision["preparedData"], notices: string[], filingSteps: string[], requiresLegalReview: boolean): ChildNameDecision { return { allowed: issues.length === 0 && resultKind !== "legalReviewOnly", outcomeKey, legalPath, resultKind, resultLabel, documentTitle, filingReady: false, requiresLegalReview, pdfAvailable: true, issues, notices, preparedData, filingSteps, draftText: "" }; }
