import { COMPLEX_MARITAL_PROPERTY_SCENARIOS, type ComplexMaritalPropertyField, type ComplexMaritalPropertyScenarioKey } from "@/data/complex-marital-property-route";
export type ComplexMaritalPropertyValues = Record<string, string | undefined>;
export type ComplexMaritalPropertyDecision = { allowed: boolean; outcomeKey: string; resultKind: "courtDraft" | "legalReviewOnly"; resultLabel: string; documentTitle: string; filingReady: false; requiresLegalReview: true; pdfAvailable: true; issues: Array<{ field: string; message: string }>; notices: string[]; preparedData: Array<{ label: string; value: string }>; filingSteps: string[]; draftText: string };
export function getVisibleComplexMaritalPropertyFields(key: ComplexMaritalPropertyScenarioKey, values: ComplexMaritalPropertyValues = {}) {
  const fields = COMPLEX_MARITAL_PROPERTY_SCENARIOS[key].helperFields;
  if (values.ordinaryOnly !== "no") return fields.slice(0, 1);
  if (values.international !== "no") return fields.slice(0, 2);
  return fields;
}
export function validateComplexMaritalProperty(key: ComplexMaritalPropertyScenarioKey, values: ComplexMaritalPropertyValues): ComplexMaritalPropertyDecision {
  const s = COMPLEX_MARITAL_PROPERTY_SCENARIOS[key]; const fields = getVisibleComplexMaritalPropertyFields(key, values); const preparedData = fields.filter((f) => values[f.name]?.trim()).map((f) => ({ label: f.label, value: display(f, values[f.name] ?? "") })); const missing = fields.filter((f) => f.required && !values[f.name]?.trim()).map((f) => ({ field: f.name, message: `Заполните поле «${f.label}».` }));
  if (missing.length) return base("missing-data", "legalReviewOnly", "Не хватает обязательных сведений", s.mainDocument, missing, preparedData, ["Материал не формируется без критических данных."], ["Заполните обязательные поля."], "");
  if (values.ordinaryOnly === "yes") return review("ordinary-division", "Используйте маршрут обычного раздела имущества", "Этот маршрут применяется только при подтверждённом сложном элементе.", preparedData);
  if (values.ordinaryOnly === "unsure") return review("complexity-unclear", "Сложный элемент не определён", "Соберите сведения об обязательствах, обременениях и правах третьих лиц до выбора маршрута.", preparedData);
  if (values.international === "yes") return review("international-route", "Требуется маршрут международного семейного спора", "Иностранные активы, участники или право требуют отдельной проверки юрисдикции и применимого права.", preparedData);
  if (values.international === "unsure") return review("international-unclear", "Иностранный элемент не определён", "Уточните местонахождение активов, участие иностранных лиц и применимое право до выбора маршрута.", preparedData);
  if (key === "debts" && values.familyUse !== "yes") return review("common-debt-not-confirmed", "Общий характер долга не подтверждён", "Нужно доказать, что обязательство возникло в интересах семьи или полученное использовано на нужды семьи.", preparedData);
  if (key === "business" && values.businessAcquired !== "yes") return review("business-origin-unclear", "Происхождение бизнес-актива не подтверждено", "Дата и основание возникновения корпоративного права определяют применимый имущественный режим.", preparedData);
  if (key === "bankruptcy-security" && (values.saleRisk !== "yes" || values.bankruptcyStatus === "unsure")) return review("security-ground-unclear", "Основание срочной меры не подтверждено", "Нужны документы о стадии дела и конкретном риске затруднения исполнения.", preparedData);
  const notices = ["Состав имущества, участников, требований, цену иска, подсудность и госпошлину проверяет юрист."];
  if (values.existingCases !== "no") notices.push("Связанные дела, аресты и исполнительные производства нужно сопоставить до выбора процессуального действия.");
  if (key === "debts" || key === "mortgage") notices.push("Внутреннее распределение между супругами не означает автоматическую замену должника перед кредитором.");
  if (key === "business") notices.push("Устав, права общества и участников и применимый вид судопроизводства требуют отдельной проверки.");
  if (key === "bankruptcy-security") notices.push("Обеспечительную меру нельзя обещать: её необходимость и соразмерность оценивает суд.");
  return base(`${key}-court-draft`, "courtDraft", "ЧЕРНОВИК — ТРЕБУЕТСЯ ЮРИДИЧЕСКАЯ ПРОВЕРКА", s.mainDocument, [], preparedData, notices, ["Передайте материал и доказательства юристу.", "Определите участников, требования, суд и связанные производства.", "Рассчитайте цену каждого требования и госпошлину.", "Подавайте документ только после проверки."], draft(values, s.mainDocument));
}
function display(field: ComplexMaritalPropertyField, value: string) { return field.options?.find((o) => o.value === value)?.label ?? value; }
function review(key: string, title: string, notice: string, data: ComplexMaritalPropertyDecision["preparedData"]) { return base(key, "legalReviewOnly", "Требуется юридическая проверка", title, [], data, [notice], [notice, "Не используйте результат как готовый судебный документ."], ""); }
function base(outcomeKey: string, resultKind: ComplexMaritalPropertyDecision["resultKind"], resultLabel: string, documentTitle: string, issues: ComplexMaritalPropertyDecision["issues"], preparedData: ComplexMaritalPropertyDecision["preparedData"], notices: string[], filingSteps: string[], draftText: string): ComplexMaritalPropertyDecision { return { allowed: !issues.length && resultKind === "courtDraft", outcomeKey, resultKind, resultLabel, documentTitle, filingReady: false, requiresLegalReview: true, pdfAvailable: true, issues, notices, preparedData, filingSteps, draftText }; }
function draft(values: ComplexMaritalPropertyValues, title: string) { return ["ЧЕРНОВИК — НЕ ГОТОВ К ПОДАЧЕ", "ТРЕБУЕТСЯ ЮРИДИЧЕСКАЯ ПРОВЕРКА", "", title.toUpperCase(), "", `Заявитель: ${values.applicant ?? ""}`, `Второй супруг: ${values.otherSpouse ?? ""}`, `Период брака: ${values.marriagePeriod ?? ""}`, `Активы и обязательства: ${values.propertyList ?? ""}`, `Источники приобретения: ${values.acquisitionSources ?? ""}`, `Оценка: ${values.valuation ?? ""}`, "", "Требования, участники, подсудность, цена иска, госпошлина и приложения определяются после юридической проверки."].join("\n"); }
