import { findGuardianshipTerritory, GUARDIANSHIP_MUNICIPALITIES, RUSSIAN_REGIONS, TERRITORY_NOT_FOUND_ID } from "@/data/guardianship-territories";
import type { ParentalDisagreementsLegalPath } from "@/data/parental-disagreements-legal-review";
import { PARENTAL_DISAGREEMENTS_SCENARIOS, type ParentalDisagreementsField, type ParentalDisagreementsScenarioKey } from "@/data/parental-disagreements-route";
export type ParentalDisagreementsValues = Record<string, string | undefined>;
export type ParentalDisagreementsIssue = { field: string; message: string };
export type ParentalDisagreementsDecision = { allowed: boolean; outcomeKey: string; legalPath: ParentalDisagreementsLegalPath; resultKind: "agreementDraft" | "applicationDraft" | "courtDraft" | "legalReviewOnly"; resultLabel: string; documentTitle: string; filingReady: false; requiresLegalReview: boolean; pdfAvailable: true; issues: ParentalDisagreementsIssue[]; notices: string[]; preparedData: Array<{ label: string; value: string }>; filingSteps: string[]; draftText: string };

export function getVisibleParentalDisagreementsFields(scenarioKey: ParentalDisagreementsScenarioKey, values: ParentalDisagreementsValues) { return PARENTAL_DISAGREEMENTS_SCENARIOS[scenarioKey].helperFields.filter((field) => { if (field.name === "childOpinion" || field.name === "childOpinionDetails") return values.childAge !== "adult" && values.childAge !== "unsure"; return true; }); }

export function validateParentalDisagreements(scenarioKey: ParentalDisagreementsScenarioKey, values: ParentalDisagreementsValues): ParentalDisagreementsDecision {
  const scenario = PARENTAL_DISAGREEMENTS_SCENARIOS[scenarioKey]; const fields = getVisibleParentalDisagreementsFields(scenarioKey, values); const preparedData = fields.filter((field) => values[field.name]?.trim()).map((field) => ({ label: field.label, value: displayValue(field, values[field.name] ?? "") })); const missing = fields.filter((field) => field.required && !values[field.name]?.trim()).map((field) => ({ field: field.name, message: `Заполните поле «${field.label}».` }));
  if (missing.length) return base("missing-data", "assessment", "legalReviewOnly", "Не хватает обязательных сведений", scenario.mainDocument, false, missing, preparedData, ["Документ не формируется без критических данных."], ["Заполните обязательные поля."], "");
  if (values.subject === "residence") return review("redirect-residence", "Нужен маршрут о месте жительства ребёнка", "Этот предмет уже реализован отдельно: «Родители и ребёнок после развода».", preparedData, "redirect");
  if (values.subject === "communication") return review("redirect-communication", "Нужен маршрут о порядке общения", "Этот предмет уже реализован отдельно: «Родители и ребёнок после развода».", preparedData, "redirect");
  if (values.childAge === "adult") return review("adult-child", "Маршрут для несовершеннолетнего неприменим", "Для совершеннолетнего лица родительские права по этому маршруту не применяются.", preparedData);
  if (values.childAge === "unsure") return review("child-age-unclear", "Возраст ребёнка не подтверждён", "Возраст влияет на применимость маршрута и обязательность учёта мнения ребёнка.", preparedData);
  if (values.immediateRisk !== "no") return review(values.immediateRisk === "yes" ? "emergency-risk" : "risk-unclear", "Обычный документный путь остановлен", values.immediateRisk === "yes" ? "При непосредственной угрозе жизни или здоровью ребёнка сначала требуется срочное обращение в экстренные службы и орган опеки; подготовка обычного документа не должна задерживать защиту ребёнка." : "Сначала уточните, есть ли непосредственная угроза ребёнку.", preparedData, "emergency");
  if (values.childAge === "10-17" && values.childOpinion !== "yes") return review(values.childOpinion === "no" ? "child-opinion-not-accounted" : "child-opinion-unclear", "Мнение ребёнка не подтверждено", "С 10 лет учёт мнения ребёнка обязателен, кроме случая противоречия его интересам.", preparedData);
  if (values.subject === "other") return review("other-subject-review", "Предмет требует юридического уточнения", "Сначала подтвердите, что вопрос относится к воспитанию или образованию и не регулируется специальным маршрутом.", preparedData);
  if (scenarioKey === "agreement") {
    if (values.parentsAgree !== "yes") return review(values.parentsAgree === "no" ? "agreement-not-reached" : "agreement-unclear", "Согласие родителей не подтверждено", "Для проекта совместного решения требуется взаимное согласие родителей.", preparedData);
    const title = values.subject === "education" ? "Проект совместного решения родителей по вопросу образования ребёнка" : "Проект совместного решения родителей по вопросу воспитания ребёнка";
    return base(`${values.subject}-agreement-draft`, "agreement", "agreementDraft", "ПРОЕКТ ДОГОВОРЁННОСТИ", title, false, [], preparedData, ["Проект не заменяет специальные заявления и решения образовательной организации или государственного органа."], ["Сверьте формулировки с фактическим решением родителей.", "Уточните специальную процедуру у организации, которая будет реализовывать решение.", "Подпишите проект только после проверки обоими родителями."], buildDraft(values, title));
  }
  if (values.parentsAgree !== "no") return review(values.parentsAgree === "yes" ? "agreement-available" : "disagreement-unclear", "Судебное или административное разногласие не подтверждено", values.parentsAgree === "yes" ? "При взаимном согласии используйте проект совместного решения родителей." : "Уточните, сохраняется ли разногласие родителей.", preparedData);
  if (scenarioKey === "guardianship") {
    const territory = findGuardianshipTerritory(values.region, values.municipality, values.authority);
    if (values.municipality === TERRITORY_NOT_FOUND_ID || values.authority === TERRITORY_NOT_FOUND_ID || !territory.authority) return review("authority-not-confirmed", "Орган опеки не подтверждён", "Найдите компетентный орган на официальном сайте региона. До подтверждения адресата обращение не формируется.", preparedData, "guardianship");
    const title = values.subject === "education" ? "Черновик обращения по разногласию родителей об образовании ребёнка" : "Черновик обращения по разногласию родителей о воспитании ребёнка";
    return base(`${values.subject}-guardianship-draft`, "guardianship", "applicationDraft", "ЧЕРНОВИК — ТРЕБУЕТ ПРОВЕРКИ", title, false, [], preparedData, ["Компетенция органа и региональный порядок подачи требуют проверки перед обращением."], ["Сверьте адресат и его компетенцию.", "Приложите документы, подтверждающие позиции родителей и интересы ребёнка.", "Уточните способ подачи на официальном сайте органа.", "Сохраните подтверждение подачи и получите письменный результат."], buildDraft(values, title, territory.authority.name));
  }
  if (values.courtConfirmed !== "yes" || !isOfficialCourtSource(values.courtSource)) return review("court-not-confirmed", "Суд не подтверждён", "Проверьте районный суд и территориальную подсудность на официальном ресурсе судебной системы.", preparedData, "court");
  const title = values.subject === "education" ? "Черновик требования о разрешении разногласия родителей по образованию ребёнка" : "Черновик требования о разрешении разногласия родителей по воспитанию ребёнка";
  return base(`${values.subject}-court-draft`, "court", "courtDraft", "ЧЕРНОВИК — НЕ ГОТОВ К ПОДАЧЕ", title, true, [], preparedData, ["Состав требования, участники, подсудность, доказательства и приложения требуют юридической проверки."], ["Проверьте точный предмет и способ защиты.", "Подтвердите суд и состав участников.", "Соберите доказательства интересов ребёнка.", "Проверьте черновик у юриста.", "Только после проверки формируйте окончательный иск."], buildDraft(values, title, values.courtName));
}
function displayValue(field: ParentalDisagreementsField, value: string) { if (field.name === "region" || field.name === "courtRegion") return RUSSIAN_REGIONS.find((region) => region.id === value)?.label ?? value; if (field.name === "municipality") return GUARDIANSHIP_MUNICIPALITIES.find((item) => item.id === value)?.name ?? value; if (field.name === "authority") return GUARDIANSHIP_MUNICIPALITIES.flatMap((item) => item.authorities).find((item) => item.id === value)?.name ?? value; return field.options?.find((option) => option.value === value)?.label ?? value; }
function isOfficialCourtSource(value?: string) { try { const host = new URL(value ?? "").hostname.toLowerCase(); return host === "sudrf.ru" || host.endsWith(".sudrf.ru") || host === "mos-gorsud.ru" || host.endsWith(".mos-gorsud.ru"); } catch { return false; } }
function review(outcomeKey: string, title: string, notice: string, preparedData: ParentalDisagreementsDecision["preparedData"], path: ParentalDisagreementsLegalPath = "assessment") { return base(outcomeKey, path, "legalReviewOnly", "Требуется юридическая проверка", title, true, [], preparedData, [notice], [notice, "Не используйте результат как готовый документ."], ""); }
function base(outcomeKey: string, legalPath: ParentalDisagreementsLegalPath, resultKind: ParentalDisagreementsDecision["resultKind"], resultLabel: string, documentTitle: string, requiresLegalReview: boolean, issues: ParentalDisagreementsIssue[], preparedData: ParentalDisagreementsDecision["preparedData"], notices: string[], filingSteps: string[], draftText: string): ParentalDisagreementsDecision { return { allowed: issues.length === 0 && resultKind !== "legalReviewOnly", outcomeKey, legalPath, resultKind, resultLabel, documentTitle, filingReady: false, requiresLegalReview, pdfAvailable: true, issues, notices, preparedData, filingSteps, draftText }; }
function buildDraft(values: ParentalDisagreementsValues, title: string, addressee?: string) { return [values.parentsAgree === "yes" ? "ПРОЕКТ ДОГОВОРЁННОСТИ — ПРОВЕРЬТЕ СПЕЦИАЛЬНУЮ ПРОЦЕДУРУ" : "ЧЕРНОВИК — НЕ ГОТОВ К ПОДАЧЕ", values.parentsAgree === "yes" ? "" : "ТРЕБУЕТСЯ ЮРИДИЧЕСКАЯ ПРОВЕРКА", addressee ? `\nВ ${addressee}` : "", "", title.toUpperCase(), "", `Первый родитель: ${values.parentOneData ?? ""}`, `Второй родитель: ${values.parentTwoData ?? ""}`, `Ребёнок: ${values.childData ?? ""}`, `Предмет: ${values.subjectDetails ?? ""}`, `Мнение ребёнка: ${values.childOpinionDetails ?? ""}`, "", "Конкретные действия, сроки, специальные заявления, просительная часть и приложения подлежат проверке по предмету решения."].filter(Boolean).join("\n"); }
