import { RUSSIAN_REGIONS } from "@/data/guardianship-territories";
import type { ParentalRightsRestrictionCancellationLegalPath } from "@/data/parental-rights-restriction-cancellation-legal-review";
import { PARENTAL_RIGHTS_RESTRICTION_CANCELLATION_SCENARIOS, type ParentalRightsRestrictionCancellationField, type ParentalRightsRestrictionCancellationScenarioKey } from "@/data/parental-rights-restriction-cancellation-route";

export type ParentalRightsRestrictionCancellationValues = Record<string, string | undefined>;
export type ParentalRightsRestrictionCancellationIssue = { field: string; message: string };
export type ParentalRightsRestrictionCancellationDecision = { allowed: boolean; outcomeKey: string; legalPath: ParentalRightsRestrictionCancellationLegalPath; resultKind: "courtDraft" | "legalReviewOnly"; resultLabel: string; documentTitle: string; filingReady: false; requiresLegalReview: true; pdfAvailable: true; issues: ParentalRightsRestrictionCancellationIssue[]; notices: string[]; preparedData: Array<{ label: string; value: string }>; filingSteps: string[]; draftText: string };

const courtFieldNames = new Set(["courtRegion", "courtName", "courtSource", "courtConfirmed"]);
export function getVisibleParentalRightsRestrictionCancellationFields(scenarioKey: ParentalRightsRestrictionCancellationScenarioKey, values: ParentalRightsRestrictionCancellationValues) {
  return PARENTAL_RIGHTS_RESTRICTION_CANCELLATION_SCENARIOS[scenarioKey].helperFields.filter((field) => {
    if (field.name === "childOpinion") return values.childAge === "10-17";
    if (scenarioKey === "readiness-review" && courtFieldNames.has(field.name)) return false;
    return true;
  });
}

export function validateParentalRightsRestrictionCancellation(scenarioKey: ParentalRightsRestrictionCancellationScenarioKey, values: ParentalRightsRestrictionCancellationValues): ParentalRightsRestrictionCancellationDecision {
  const scenario = PARENTAL_RIGHTS_RESTRICTION_CANCELLATION_SCENARIOS[scenarioKey];
  const fields = getVisibleParentalRightsRestrictionCancellationFields(scenarioKey, values);
  const preparedData = fields.filter((field) => values[field.name]?.trim()).map((field) => ({ label: field.label, value: displayValue(field, values[field.name] ?? "") }));
  const missing = fields.filter((field) => field.required && !values[field.name]?.trim()).map((field) => ({ field: field.name, message: `Заполните поле «${field.label}».` }));
  if (missing.length) return base("missing-data", "assessment", "legalReviewOnly", "Не хватает обязательных сведений", scenario.mainDocument, missing, preparedData, ["Без критических данных судебный черновик не формируется."], ["Заполните обязательные поля и повторите проверку."], "");
  if (values.restrictionDecision !== "yes") return review(values.restrictionDecision === "no" ? "no-restriction-decision" : "restriction-decision-unclear", "Действующее ограничение не подтверждено", "Статья 76 СК РФ применяется к родителю, ограниченному в правах вступившим в силу решением суда. После лишения прав используйте отдельный маршрут восстановления.", preparedData);
  if (values.childAge === "adult") return review("adult-child", "Ребёнок достиг совершеннолетия", "Маршрут отмены ограничения в отношении несовершеннолетнего неприменим без отдельного правового основания.", preparedData);
  if (values.childAge === "unsure") return review("child-age-unclear", "Возраст ребёнка не подтверждён", "Возраст влияет на применимость маршрута и порядок выяснения мнения ребёнка.", preparedData);
  if (values.groundsCeased !== "yes") return review(values.groundsCeased === "no" ? "grounds-remain" : "grounds-unclear", "Отпадение оснований не подтверждено", "Суд может отменить ограничение, только если основания, по которым оно было установлено, отпали.", preparedData);
  if (values.newRisks !== "no") return review(values.newRisks === "yes" ? "current-risks" : "risks-unclear", "Требуется оценить текущие риски", "Новые или сохраняющиеся риски требуют индивидуальной оценки до подготовки иска.", preparedData);
  if (values.childAge === "10-17" && values.childOpinion !== "supports") return review(values.childOpinion === "objects" ? "child-objects" : "child-opinion-unclear", "Позиция ребёнка требует оценки", "Суд учитывает мнение ребёнка; возражение не подменяется автоматическим выводом, но требует юридической оценки интересов ребёнка.", preparedData);
  if (scenarioKey === "readiness-review") return review("conditions-appear-confirmed", "Условия требуют судебной проверки", "Для подготовки судебного черновика выберите основной сценарий и заполните сведения о сторонах и суде.", preparedData);
  if (values.courtConfirmed !== "yes" || !isOfficialCourtSource(values.courtSource)) return review("court-not-confirmed", "Суд не подтверждён", "Используйте официальную страницу судебной системы и проверьте территориальную подсудность.", preparedData, scenarioKey === "cancellation-return" ? "return" : "court");
  const title = scenarioKey === "cancellation-return" ? "Черновик иска об отмене ограничения родительских прав и возврате ребёнка" : "Черновик иска об отмене ограничения родительских прав";
  return base(`${scenarioKey}-court-draft`, scenarioKey === "cancellation-return" ? "return" : "court", "courtDraft", "ЧЕРНОВИК — НЕ ГОТОВ К ПОДАЧЕ", title, [], preparedData, ["Требуются проверка подсудности, состава участников, доказательств, просительной части и приложений."], ["Сверьте полный текст решения об ограничении.", "Проверьте доказательства отпадения оснований и отсутствие новых рисков.", "Подтвердите ответчика, орган опеки, прокурора и суд.", "Проверьте черновик у юриста.", "Только после проверки формируйте окончательный иск и приложения."], buildCourtDraft(values, title, scenarioKey === "cancellation-return"));
}

function displayValue(field: ParentalRightsRestrictionCancellationField, value: string) { if (field.name === "courtRegion") return RUSSIAN_REGIONS.find((region) => region.id === value)?.label ?? value; return field.options?.find((option) => option.value === value)?.label ?? value; }
function isOfficialCourtSource(value?: string) { try { const host = new URL(value ?? "").hostname.toLowerCase(); return host === "sudrf.ru" || host.endsWith(".sudrf.ru") || host === "mos-gorsud.ru" || host.endsWith(".mos-gorsud.ru"); } catch { return false; } }
function review(outcomeKey: string, title: string, notice: string, preparedData: ParentalRightsRestrictionCancellationDecision["preparedData"], path: ParentalRightsRestrictionCancellationLegalPath = "assessment") { return base(outcomeKey, path, "legalReviewOnly", "Требуется юридическая проверка", title, [], preparedData, [notice], [notice, "Не используйте результат как исковое заявление."], ""); }
function base(outcomeKey: string, legalPath: ParentalRightsRestrictionCancellationLegalPath, resultKind: ParentalRightsRestrictionCancellationDecision["resultKind"], resultLabel: string, documentTitle: string, issues: ParentalRightsRestrictionCancellationIssue[], preparedData: ParentalRightsRestrictionCancellationDecision["preparedData"], notices: string[], filingSteps: string[], draftText: string): ParentalRightsRestrictionCancellationDecision { return { allowed: issues.length === 0 && resultKind === "courtDraft", outcomeKey, legalPath, resultKind, resultLabel, documentTitle, filingReady: false, requiresLegalReview: true, pdfAvailable: true, issues, notices, preparedData, filingSteps, draftText }; }
function buildCourtDraft(values: ParentalRightsRestrictionCancellationValues, title: string, includeReturn: boolean) { return ["ЧЕРНОВИК — НЕ ГОТОВ К ПОДАЧЕ", "ТРЕБУЕТСЯ ЮРИДИЧЕСКАЯ ПРОВЕРКА", "", `В ${values.courtName ?? "[суд требует проверки]"}`, "", `Истец: ${values.applicantData ?? ""}`, `Ответчик: ${values.caregiverData ?? ""}`, `Ребёнок: ${values.childData ?? ""}`, "", title.toUpperCase(), "", `Решение об ограничении: ${values.decisionDetails ?? ""}`, `Отпадение оснований и доказательства: ${values.changeEvidence ?? ""}`, `Интересы ребёнка: ${values.childInterests ?? ""}`, includeReturn ? `Основания требования о возврате ребёнка: ${values.returnBasis ?? ""}` : "", includeReturn ? `Условия проживания, ухода и воспитания: ${values.livingConditions ?? ""}` : "", "", "Просительная часть, состав участников, мнение ребёнка, заключение органа опеки, доказательства и приложения требуют юридической проверки."].filter(Boolean).join("\n"); }
