import assert from "node:assert/strict";
import { getParentalRightsRestrictionCancellationRules } from "@/data/parental-rights-restriction-cancellation-legal-review";
import { PARENTAL_RIGHTS_RESTRICTION_CANCELLATION_SCENARIO_KEYS } from "@/data/parental-rights-restriction-cancellation-route";
import { ensureParentalRightsRestrictionCancellationDraftMarker } from "@/lib/parental-rights-restriction-cancellation-docx";
import { buildParentalRightsRestrictionCancellationPdfText } from "@/lib/parental-rights-restriction-cancellation-pdf";
import { getVisibleParentalRightsRestrictionCancellationFields, validateParentalRightsRestrictionCancellation } from "@/lib/parental-rights-restriction-cancellation-validator";

const base = { restrictionDecision: "yes", decisionDetails: "Решение районного суда от 01.02.2025, дело № 1", groundsCeased: "yes", changeEvidence: "Документы об устранении обстоятельств", newRisks: "no", childAge: "under-10", childInterests: "Восстановлены безопасные условия", applicantData: "Иванов Иван, дата рождения, адрес, паспорт", caregiverData: "Иванова Анна, адрес", childData: "Иванов Пётр, 2018 года рождения, адрес", courtRegion: "region-moscow", courtName: "Тверской районный суд города Москвы", courtSource: "https://tverskoy.msk.sudrf.ru/", courtConfirmed: "yes" };
const outcomes = new Set<string>();
const record = (decision: ReturnType<typeof validateParentalRightsRestrictionCancellation>) => { outcomes.add(decision.outcomeKey); return decision; };
const cancellation = record(validateParentalRightsRestrictionCancellation("cancellation", base));
assert.equal(cancellation.resultKind, "courtDraft"); assert.equal(cancellation.filingReady, false); assert.equal(cancellation.requiresLegalReview, true); assert.match(cancellation.draftText, /ЧЕРНОВИК — НЕ ГОТОВ К ПОДАЧЕ/); assert.match(buildParentalRightsRestrictionCancellationPdfText(cancellation), /Готово к подаче: нет/); assert.match(ensureParentalRightsRestrictionCancellationDraftMarker("Текст"), /ЧЕРНОВИК — НЕ ГОТОВ К ПОДАЧЕ/);
const withReturn = record(validateParentalRightsRestrictionCancellation("cancellation-return", { ...base, returnBasis: "Возвращение отвечает интересам ребёнка", livingConditions: "Обеспечены жильё и уход" })); assert.equal(withReturn.legalPath, "return"); assert.match(withReturn.draftText, /Основания требования о возврате/);
assert.equal(record(validateParentalRightsRestrictionCancellation("cancellation", { ...base, restrictionDecision: "no" })).outcomeKey, "no-restriction-decision");
assert.equal(record(validateParentalRightsRestrictionCancellation("cancellation", { ...base, childAge: "adult" })).outcomeKey, "adult-child");
assert.equal(record(validateParentalRightsRestrictionCancellation("cancellation", { ...base, groundsCeased: "no" })).outcomeKey, "grounds-remain");
assert.equal(record(validateParentalRightsRestrictionCancellation("cancellation", { ...base, newRisks: "yes" })).outcomeKey, "current-risks");
assert.equal(record(validateParentalRightsRestrictionCancellation("cancellation", { ...base, childAge: "10-17", childOpinion: "objects" })).outcomeKey, "child-objects");
assert.equal(record(validateParentalRightsRestrictionCancellation("cancellation", { ...base, courtSource: "https://example.com/" })).outcomeKey, "court-not-confirmed");
assert.equal(record(validateParentalRightsRestrictionCancellation("readiness-review", { restrictionDecision: "yes", decisionDetails: base.decisionDetails, groundsCeased: "yes", changeEvidence: base.changeEvidence, newRisks: "no", childAge: "under-10", childInterests: base.childInterests })).outcomeKey, "conditions-appear-confirmed");
assert.equal(record(validateParentalRightsRestrictionCancellation("cancellation", {})).outcomeKey, "missing-data");
assert.equal(getVisibleParentalRightsRestrictionCancellationFields("cancellation", { childAge: "under-10" }).some((field) => field.name === "childOpinion"), false);
assert.equal(getVisibleParentalRightsRestrictionCancellationFields("cancellation", { childAge: "10-17" }).some((field) => field.name === "childOpinion"), true);
for (const key of PARENTAL_RIGHTS_RESTRICTION_CANCELLATION_SCENARIO_KEYS) assert.equal(getParentalRightsRestrictionCancellationRules(key).length > 0, true);
console.log(`Parental-rights restriction cancellation validation passed: ${outcomes.size} reachable outcomes.`);
