import type { PrenuptialAgreementLegalPath } from "@/data/prenuptial-agreement-legal-review";
import { PRENUPTIAL_AGREEMENT_SCENARIOS, type PrenuptialAgreementField, type PrenuptialAgreementScenarioKey } from "@/data/prenuptial-agreement-route";
export type PrenuptialAgreementValues = Record<string, string | undefined>;
export type PrenuptialAgreementDecision = { allowed: boolean; outcomeKey: string; legalPath: PrenuptialAgreementLegalPath; resultKind: "agreementDraft" | "courtDraft" | "legalReviewOnly"; resultLabel: string; documentTitle: string; filingReady: false; requiresLegalReview: true; pdfAvailable: true; issues: Array<{ field: string; message: string }>; notices: string[]; preparedData: Array<{ label: string; value: string }>; filingSteps: string[]; draftText: string };
export function getVisiblePrenuptialAgreementFields(scenarioKey: PrenuptialAgreementScenarioKey, _values: PrenuptialAgreementValues) { return PRENUPTIAL_AGREEMENT_SCENARIOS[scenarioKey].helperFields; }
export function validatePrenuptialAgreement(scenarioKey: PrenuptialAgreementScenarioKey, values: PrenuptialAgreementValues): PrenuptialAgreementDecision {
  const scenario = PRENUPTIAL_AGREEMENT_SCENARIOS[scenarioKey]; const preparedData = scenario.helperFields.filter((f) => values[f.name]?.trim()).map((f) => ({ label: f.label, value: display(f, values[f.name] ?? "") })); const missing = scenario.helperFields.filter((f) => f.required && !values[f.name]?.trim()).map((f) => ({ field: f.name, message: `Заполните поле «${f.label}».` }));
  if (missing.length) return base("missing-data", "review", "legalReviewOnly", "Не хватает обязательных сведений", scenario.mainDocument, missing, preparedData, ["Документ не формируется без критических данных."], ["Заполните обязательные поля."], "");
  if (values.international !== "no" || values.thirdPartyRisk !== "no") return review("complex-risk", "Нужна проверка сложных обстоятельств", "Иностранный элемент, кредиторы, банкротство, корпоративные активы или права третьих лиц требуют отдельного анализа.", preparedData);
  const forbiddenNames = ["personalTerms", "childTerms", "capacityRestriction", "courtRestriction", "supportRestriction"];
  const forbidden = forbiddenNames.find((name) => values[name] !== "no");
  const prohibitedTermDispute = scenarioKey === "dispute" && values.disputeGround === "prohibited-term" && forbiddenNames.some((name) => values[name] === "yes") && forbiddenNames.every((name) => values[name] === "yes" || values[name] === "no");
  if (forbidden && !prohibitedTermDispute) return review("prohibited-or-unclear-term", "Условие запрещено или неясно", "Проект нельзя формировать, пока не исключены запреты пункта 3 статьи 42 СК РФ.", preparedData);
  const extremeDisadvantageDispute = scenarioKey === "dispute" && values.disputeGround === "extreme-disadvantage" && values.extremeDisadvantage === "yes";
  if (values.extremeDisadvantage !== "no" && !extremeDisadvantageDispute) return review("extreme-disadvantage-review", "Требуется оценка положения сторон", "Крайне неблагоприятное положение оценивается индивидуально; помощник не подтверждает его отсутствие.", preparedData);
  if (scenarioKey === "before" && values.marriagePlanned !== "yes") return review("marriage-not-confirmed", "Намерение зарегистрировать брак не подтверждено", "Брачный договор до брака вступит в силу только со дня государственной регистрации брака.", preparedData);
  if (scenarioKey === "during" && values.marriageRegistered !== "yes") return review("marriage-not-registered", "Действующий брак не подтверждён", "Заключить брачный договор как супруги можно только в зарегистрированном браке.", preparedData);
  if ((scenarioKey === "change" || scenarioKey === "terminate") && values.agreementExists !== "yes") return review("existing-contract-not-confirmed", "Действующий нотариальный договор не подтверждён", "Сначала подтвердите существование и содержание нотариально удостоверенного договора.", preparedData);
  if (scenarioKey !== "dispute") {
    if (values.bothAgree !== "yes") return review("consent-not-confirmed", "Согласие обеих сторон не подтверждено", "Односторонний отказ не допускается; спорное изменение или расторжение требует отдельного судебного анализа.", preparedData);
    const title = scenario.mainDocument; return base(`${scenarioKey}-notary-project`, "notary", "agreementDraft", "ПРОЕКТ ДЛЯ НОТАРИУСА", title, [], preparedData, ["Проект не заменяет нотариально удостоверенный документ."], ["Сверьте перечень имущества и обязательств.", "Передайте проект и документы нотариусу.", "Подписывайте окончательный текст только в установленном нотариусом порядке."], draft(values, title));
  }
  if (values.agreementExists !== "yes") return review("existing-contract-not-confirmed", "Договор не подтверждён", "Для судебного спора нужен текст и сведения о нотариальном удостоверении договора.", preparedData);
  if (values.disputeGround === "other") return review("dispute-ground-unclear", "Основание спора не подтверждено", "Нельзя формировать судебное требование без определённого правового основания.", preparedData);
  if (values.courtConfirmed !== "yes" || !officialCourt(values.courtSource)) return review("court-not-confirmed", "Суд не подтверждён", "Проверьте суд на официальном ресурсе судебной системы.", preparedData);
  const title = "Черновик требования по спору о брачном договоре"; return base(`dispute-${values.disputeGround}-court-draft`, "court", "courtDraft", "ЧЕРНОВИК — ТРЕБУЕТСЯ ЮРИДИЧЕСКАЯ ПРОВЕРКА", title, [], preparedData, ["Основание, срок, последствия, подсудность и затронутые лица проверяются до подачи."], ["Передайте договор и доказательства юристу.", "Проверьте основание, срок и последствия.", "Проверьте суд, цену иска и госпошлину."], draft(values, title, values.courtName));
}
function display(field: PrenuptialAgreementField, value: string) { return field.options?.find((o) => o.value === value)?.label ?? value; }
function officialCourt(value?: string) { try { const h = new URL(value ?? "").hostname.toLowerCase(); return h === "sudrf.ru" || h.endsWith(".sudrf.ru") || h === "mos-gorsud.ru" || h.endsWith(".mos-gorsud.ru"); } catch { return false; } }
function review(key: string, title: string, notice: string, data: PrenuptialAgreementDecision["preparedData"]) { return base(key, "review", "legalReviewOnly", "Требуется юридическая проверка", title, [], data, [notice], [notice, "Не используйте результат как готовый документ."], ""); }
function base(outcomeKey: string, legalPath: PrenuptialAgreementLegalPath, resultKind: PrenuptialAgreementDecision["resultKind"], resultLabel: string, documentTitle: string, issues: PrenuptialAgreementDecision["issues"], preparedData: PrenuptialAgreementDecision["preparedData"], notices: string[], filingSteps: string[], draftText: string): PrenuptialAgreementDecision { return { allowed: !issues.length && resultKind !== "legalReviewOnly", outcomeKey, legalPath, resultKind, resultLabel, documentTitle, filingReady: false, requiresLegalReview: true, pdfAvailable: true, issues, notices, preparedData, filingSteps, draftText }; }
function draft(v: PrenuptialAgreementValues, title: string, addressee?: string) { return ["ЧЕРНОВИК — НЕ ГОТОВ К ПОДПИСАНИЮ ИЛИ ПОДАЧЕ", "ТРЕБУЕТСЯ ЮРИДИЧЕСКАЯ ПРОВЕРКА", addressee ? `\nВ ${addressee}` : "", "", title.toUpperCase(), "", `Сторона 1: ${v.partyOne ?? ""}`, `Сторона 2: ${v.partyTwo ?? ""}`, `Имущество и обязательства: ${v.assets ?? ""}`, `Предлагаемые условия: ${v.propertyTerms ?? ""}`, v.disputeFacts ? `Обстоятельства спора: ${v.disputeFacts}` : "", "", "Точный текст, последствия и приложения подлежат проверке нотариусом или юристом."].filter(Boolean).join("\n"); }
