ALTER TYPE "QualityStatus" ADD VALUE IF NOT EXISTS 'NEEDS_REVIEW';

ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'LEAD_CREATED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'QUESTION_SUBMITTED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'LAWYER_PROFILE_FORM_OPENED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'LAWYER_PROFILE_LEAD_CREATED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'CONSULTATION_REQUEST_CREATED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'DOCUMENT_ORDER_CREATED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'CALCULATOR_COMPLETED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'CHECKLIST_DOWNLOADED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'DOCUMENT_REVIEW_REQUEST_CREATED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'CITY_SERVICE_LEAD_CREATED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'ARTICLE_CTA_CLICKED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'STICKY_CTA_CLICKED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'PLATFORM_PHONE_CLICKED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'PLATFORM_EMAIL_CLICKED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'PLATFORM_MESSENGER_CLICKED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'CONTACTS_PAGE_OPENED';

CREATE TYPE "LeadSourceType" AS ENUM (
  'GENERAL',
  'LAWYER_PROFILE',
  'CITY_SERVICE',
  'ARTICLE',
  'DOCUMENT',
  'CALCULATOR',
  'CHECKLIST',
  'CONTACTS',
  'DOCUMENT_REVIEW'
);

ALTER TABLE "Lead" ADD COLUMN "sourceType" "LeadSourceType" NOT NULL DEFAULT 'GENERAL';
CREATE INDEX "Lead_sourceType_createdAt_idx" ON "Lead"("sourceType", "createdAt");
