ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CONTACTED';

ALTER TYPE "LeadSourceType" ADD VALUE IF NOT EXISTS 'SERVICE_PAGE';
ALTER TYPE "LeadSourceType" ADD VALUE IF NOT EXISTS 'CITY_PAGE';
ALTER TYPE "LeadSourceType" ADD VALUE IF NOT EXISTS 'CITY_SERVICE_PAGE';
ALTER TYPE "LeadSourceType" ADD VALUE IF NOT EXISTS 'QUESTION';

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "adminComment" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
