import { expect, test } from "@playwright/test";
const problemPath = "/problems/semya-i-deti/emansipatsiya-nesovershennoletnego/"; const documentPath = "/documents/emansipatsiya-nesovershennoletnego-materialy/";
test("emancipation landing has four paths", async ({ page }) => { await page.goto(problemPath); await expect(page.getByRole("heading", { level: 1, name: "Эмансипация несовершеннолетнего" })).toHaveCount(1); for (const key of ["eligibility", "guardianship", "court", "consequences"]) await expect(page.locator(`a[href$="?scenario=${key}"]`)).toBeVisible(); });
test("query state is noindex", async ({ page }) => { await page.goto(`${problemPath}?scenario=court`); await expect(page.locator('meta[name="robots"]')).toHaveAttribute("content", /noindex/); await expect(page.getByRole("link", { name: "Подготовить материал" })).toHaveAttribute("href", `${documentPath}?variant=court#fill-online`); });
test("age alone does not unlock PDF", async ({ page }) => { await page.goto(`${documentPath}?variant=eligibility`); await page.getByLabel("Возраст несовершеннолетнего").selectOption("16"); await page.getByLabel("На каком основании несовершеннолетний работает?").selectOption("none"); await page.getByLabel("Реквизиты трудового договора или регистрации предпринимательства").fill("Нет"); await page.getByLabel("Есть согласие обоих родителей, усыновителей или попечителя?").selectOption("all"); await page.getByRole("button", { name: "Подготовить результат" }).click(); await expect(page.getByText(/Не подтверждено основание занятости/)).toBeVisible(); await expect(page.getByRole("button", { name: "Скачать PDF" })).toHaveCount(0); });
test("court path stays a reviewed draft", async ({ page }) => { await page.goto(`${documentPath}?variant=court`); await page.getByLabel("Возраст несовершеннолетнего").selectOption("16"); await page.getByLabel("На каком основании несовершеннолетний работает?").selectOption("employment"); for (const area of await page.locator("textarea").all()) await area.fill("Проверочное значение"); await page.getByLabel("Необходимое согласие законных представителей отсутствует?").selectOption("missing"); await page.getByRole("button", { name: "Подготовить результат" }).click(); await expect(page.getByText(/Юридическая проверка обязательна/)).toBeVisible(); await expect(page.getByRole("button", { name: "Скачать PDF" })).toBeVisible(); });
test("territory cascade works", async ({ page }) => { await page.goto(`${documentPath}?variant=guardianship`); const region = page.getByRole("combobox", { name: "Регион проживания" }); await region.fill("Санкт"); await region.press("ArrowDown"); await region.press("Enter"); const municipality = page.getByRole("combobox", { name: "Муниципальное образование" }); await municipality.fill("Гагарин"); await municipality.press("ArrowDown"); await municipality.press("Enter"); await expect(page.getByRole("combobox", { name: "Орган опеки и попечительства" })).toBeEnabled(); });
test("pages fit supported widths", async ({ page }) => { for (const width of [320, 375, 768, 1440]) { await page.setViewportSize({ width, height: 900 }); for (const path of [problemPath, documentPath]) { await page.goto(path); expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false); } } });
test("unknown route is 404", async ({ page }) => { const response = await page.goto(`${problemPath}unknown/`); expect(response?.status()).toBe(404); });
