import { expect, test } from "@playwright/test";
const problemPath = "/problems/semya-i-deti/obshchenie-rodstvennikov-s-rebenkom/"; const documentPath = "/documents/obshchenie-rodstvennikov-s-rebenkom-materialy/";
test("relative contact landing has four distinct paths", async ({ page }) => { await page.goto(problemPath); await expect(page.getByRole("heading", { level: 1, name: "Общение родственников с ребёнком" })).toHaveCount(1); for (const key of ["agreement", "guardianship", "court", "enforcement"]) await expect(page.locator(`a[href$="?scenario=${key}"]`)).toBeVisible(); });
test("query state is noindex", async ({ page }) => { await page.goto(`${problemPath}?scenario=guardianship`); await expect(page.locator('meta[name="robots"]')).toHaveAttribute("content", /noindex/); await expect(page.getByRole("link", { name: "Подготовить материал" })).toHaveAttribute("href", `${documentPath}?variant=guardianship#fill-online`); });
test("parent is routed to parent reference route", async ({ page }) => { await page.goto(`${documentPath}?variant=agreement`); await page.getByLabel("Кем вы приходитесь ребёнку?").selectOption("parent"); for (const area of await page.locator("textarea").all()) await area.fill("Проверочное значение"); await page.getByLabel("Есть непосредственная угроза жизни или здоровью ребёнка?").selectOption("no"); await page.getByLabel("Родители или законный представитель согласны обсуждать порядок общения?").selectOption("yes"); await page.getByRole("button", { name: "Подготовить результат" }).click(); await expect(page.getByRole("link", { name: "Перейти к маршруту для родителей" })).toHaveAttribute("href", "/problems/semya-i-deti/roditeli-i-rebenok-posle-razvoda/"); await expect(page.getByRole("button", { name: "Скачать PDF" })).toHaveCount(0); });
test("court path stays a reviewed draft", async ({ page }) => { await page.goto(`${documentPath}?variant=court`); await page.getByLabel("Кем вы приходитесь ребёнку?").selectOption("grandparent"); for (const area of await page.locator("textarea").all()) await area.fill("Проверочное значение"); await page.getByLabel("Есть непосредственная угроза жизни или здоровью ребёнка?").selectOption("no"); await page.getByLabel("Орган опеки уже вынес решение об устранении препятствий?").selectOption("yes"); await page.getByRole("button", { name: "Подготовить результат" }).click(); await expect(page.getByText(/Юридическая проверка обязательна/)).toBeVisible(); await expect(page.getByRole("button", { name: "Скачать PDF" })).toBeVisible(); });
test("territory cascade is searchable and clears dependants", async ({ page }) => { await page.goto(`${documentPath}?variant=guardianship`); const region = page.getByRole("combobox", { name: "Регион проживания ребёнка" }); await region.fill("Санкт"); await region.press("ArrowDown"); await region.press("Enter"); const municipality = page.getByRole("combobox", { name: "Муниципальное образование" }); await municipality.fill("Гагарин"); await municipality.press("ArrowDown"); await municipality.press("Enter"); await expect(page.getByRole("combobox", { name: "Орган опеки и попечительства" })).toBeEnabled(); });
test("pages fit supported widths", async ({ page }) => { for (const width of [320, 375, 768, 1440]) { await page.setViewportSize({ width, height: 900 }); for (const path of [problemPath, documentPath]) { await page.goto(path); expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false); } } });
test("unknown route is 404", async ({ page }) => { const response = await page.goto(`${problemPath}unknown/`); expect(response?.status()).toBe(404); });
