-- Pravopoisk public content snapshot
-- This file defines the portable Git-safe snapshot format.
-- Data is generated by scripts/export-public-content-snapshot.sh from production PostgreSQL.
-- Raw production backups, users, leads, emails, private attachments, auth data and audit logs
-- MUST NOT be committed to the public repository.

BEGIN;

CREATE SCHEMA IF NOT EXISTS pravopoisk_public_snapshot;

CREATE TABLE IF NOT EXISTS pravopoisk_public_snapshot.records (
  source_table text NOT NULL,
  source_id text NOT NULL,
  data jsonb NOT NULL,
  exported_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_table, source_id)
);

CREATE INDEX IF NOT EXISTS pravopoisk_public_snapshot_records_table_idx
  ON pravopoisk_public_snapshot.records (source_table);

COMMIT;

-- The generated snapshot appends COPY blocks after this schema.
