ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'QUESTION_WIZARD_STARTED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'QUESTION_WIZARD_CLARIFICATIONS_SHOWN';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'QUESTION_WIZARD_ENRICHED_CONFIRMED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'QUESTION_WIZARD_ANALYZING_STARTED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'QUESTION_WIZARD_PRELIMINARY_READY';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'QUESTION_WIZARD_ANALYZING_TIMEOUT';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'QUESTION_WIZARD_TRANSFER_TO_LAWYER_CLICKED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'QUESTION_WIZARD_LEAD_CREATED';

ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "rawText" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "enrichedTitle" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "enrichedText" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "enrichmentStatus" TEXT NOT NULL DEFAULT 'RAW';
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "preliminaryAnswer" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "preliminaryAnswerStatus" TEXT NOT NULL DEFAULT 'NOT_REQUESTED';
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "scenarioId" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "legalStage" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "urgency" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "riskLevel" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "facts" JSONB;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "missingFacts" JSONB;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "clarificationAnswers" JSONB;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "leadScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "seoQualityScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "userConfirmedEnrichmentAt" TIMESTAMP(3);
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "aiAssisted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "editorReviewedAt" TIMESTAMP(3);
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "indexabilityReason" TEXT;

ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "containsUnsupportedLegalClaim" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "containsFearPressure" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "containsGenericLeadBait" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "legalReferencesVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "answerReviewStatus" TEXT;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "answerReviewReason" TEXT;
ALTER TABLE "Answer" ADD COLUMN IF NOT EXISTS "editorReviewedAt" TIMESTAMP(3);

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "questionId" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "messenger" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "availableTime" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "documentsNote" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "structuredPayload" JSONB;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "leadScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "contactTransferConsentAt" TIMESTAMP(3);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Lead_questionId_fkey'
  ) THEN
    ALTER TABLE "Lead"
      ADD CONSTRAINT "Lead_questionId_fkey"
      FOREIGN KEY ("questionId") REFERENCES "Question"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "Question_scenarioId_idx" ON "Question"("scenarioId");
CREATE INDEX IF NOT EXISTS "Answer_answerReviewStatus_idx" ON "Answer"("answerReviewStatus");
CREATE INDEX IF NOT EXISTS "Lead_questionId_idx" ON "Lead"("questionId");
