"use client";
import { useState } from "react";
import Link from "next/link";
import { Download, ShieldCheck } from "lucide-react";
import { SearchableSelect } from "@/components/forms/SearchableSelect";
import { GUARDIANSHIP_DIRECTORY_METADATA, TERRITORY_NOT_FOUND_ID, findGuardianshipTerritory, getGuardianshipAuthorityOptions, getGuardianshipMunicipalityOptions, getGuardianshipRegionOptions } from "@/data/guardianship-territories";
import { EMANCIPATION_KEYS, EMANCIPATION_SCENARIOS, type EmancipationField, type EmancipationKey } from "@/data/emancipation-route";
import { createEmancipationPdfBlob } from "@/lib/emancipation-pdf";
import { validateEmancipation, type EmancipationDecision, type EmancipationValues } from "@/lib/emancipation-validator";

export function EmancipationHelper({ initialKey }: { initialKey?: EmancipationKey }) {
  const [key, setKey] = useState<EmancipationKey | "">(initialKey ?? ""); const [values, setValues] = useState<EmancipationValues>({}); const [decision, setDecision] = useState<EmancipationDecision | null>(null); const [message, setMessage] = useState(""); const scenario = key ? EMANCIPATION_SCENARIOS[key] : null;
  function update(name: string, value: string) { setValues((current) => { const next = { ...current, [name]: value }; if (name === "region") { delete next.municipality; delete next.authorityName; } if (name === "municipality") delete next.authorityName; return next; }); setDecision(null); setMessage(""); }
  async function download() { if (!decision?.pdfAvailable) return; try { const blob = await createEmancipationPdfBlob(decision); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `emancipation-${key}.pdf`; anchor.click(); URL.revokeObjectURL(url); setMessage("PDF скачан. Проверьте его статус готовности."); } catch { setMessage("Не удалось сформировать PDF. Попробуйте ещё раз."); } }
  return <section id="fill-online" className="scroll-mt-24 border border-line bg-white p-5 shadow-sm sm:p-6"><h2 className="text-2xl font-semibold text-ink">Подготовить материал</h2><p className="mt-2 text-sm leading-6 text-zinc-700">Выберите стадию. Шестнадцатилетие само по себе не означает эмансипацию.</p>
    <div className="mt-5 grid gap-2"><label htmlFor="emancipation-scenario" className="text-sm font-semibold text-ink">Что нужно сделать?</label><select id="emancipation-scenario" value={key} onChange={(event) => { setKey(event.target.value as EmancipationKey | ""); setValues({}); setDecision(null); }} className="min-h-11 w-full rounded-md border border-line bg-white px-3 py-2 text-base"><option value="">Выберите ситуацию</option>{EMANCIPATION_KEYS.map((item) => <option value={item} key={item}>{EMANCIPATION_SCENARIOS[item].title}</option>)}</select></div>
    {scenario ? <form className="mt-6 grid gap-5" onSubmit={(event) => { event.preventDefault(); setDecision(validateEmancipation(scenario.key, values)); }}>{scenario.questions.map((field) => <Field key={field.name} field={field} values={values} update={update} />)}<button type="submit" className="inline-flex min-h-11 w-fit items-center rounded-md bg-trust px-5 py-3 text-sm font-semibold text-white">Подготовить результат</button></form> : null}
    {decision ? <div className="mt-6 border-t border-line pt-5" aria-live="polite"><h3 className="text-xl font-semibold text-ink">{decision.resultLabel}</h3><p className="mt-2 text-sm font-semibold text-amber-900">Готово к подаче: нет. {decision.requiresLegalReview ? "Юридическая проверка обязательна." : "Сначала выполните указанные шаги."}</p>{decision.issues.map((issue) => <p key={`${issue.field}-${issue.message}`} className="mt-2 text-sm text-red-800">{issue.message}</p>)}{decision.notices.map((notice) => <p key={notice} className="mt-2 text-sm leading-6 text-zinc-700">{notice}</p>)}{decision.pdfAvailable ? <><h4 className="mt-5 font-semibold text-ink">Что собрать</h4><ul className="mt-2 grid gap-2 text-sm leading-6 text-zinc-700">{decision.evidence.map((item) => <li key={item}>- {item}</li>)}</ul><h4 className="mt-5 font-semibold text-ink">Что делать дальше</h4><ol className="mt-2 grid gap-2 text-sm leading-6 text-zinc-700">{decision.nextSteps.map((item, index) => <li key={item}>{index + 1}. {item}</li>)}</ol><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={download} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-trust px-5 py-3 text-sm font-semibold text-white"><Download className="h-4 w-4" aria-hidden="true" /> Скачать PDF</button><Link href="/questions/#question" className="inline-flex min-h-11 items-center gap-2 rounded-md border border-trust px-5 py-3 text-sm font-semibold text-trust"><ShieldCheck className="h-4 w-4" aria-hidden="true" /> Проверить у юриста</Link></div></> : null}{message ? <p role="status" className="mt-3 text-sm text-zinc-700">{message}</p> : null}</div> : null}
  </section>;
}

function Field({ field, values, update }: { field: EmancipationField; values: EmancipationValues; update: (name: string, value: string) => void }) {
  const id = `emancipation-${field.name}`; const value = values[field.name] ?? ""; const territorial = field.type === "territory-region" || field.type === "territory-municipality" || field.type === "guardianship-authority";
  const options = field.type === "territory-region" ? getGuardianshipRegionOptions() : field.type === "territory-municipality" ? getGuardianshipMunicipalityOptions(values.region) : field.type === "guardianship-authority" ? getGuardianshipAuthorityOptions(values.municipality) : []; const authority = field.type === "guardianship-authority" ? findGuardianshipTerritory(values.region, values.municipality, value).authority : undefined;
  return <div className="grid gap-2"><label htmlFor={id} className="text-sm font-semibold text-ink">{field.label}</label>{territorial ? <SearchableSelect id={id} label={field.label} options={options} value={value} onChange={(selected) => update(field.name, selected)} required disabled={field.type === "territory-municipality" ? !values.region : field.type === "guardianship-authority" ? !values.municipality || values.municipality === TERRITORY_NOT_FOUND_ID : false} placeholder={field.type === "territory-region" ? "Выберите регион" : field.type === "territory-municipality" ? "Выберите муниципальное образование" : "Выберите орган опеки"} searchPlaceholder={`Поиск: ${field.label.toLowerCase()}`} /> : field.type === "select" ? <select id={id} value={value} onChange={(event) => update(field.name, event.target.value)} className="min-h-11 w-full rounded-md border border-line bg-white px-3 py-2 text-base" required><option value="">Выберите вариант</option>{field.options?.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select> : <textarea id={id} value={value} onChange={(event) => update(field.name, event.target.value)} rows={3} className="min-h-24 w-full rounded-md border border-line bg-white px-3 py-2 text-base" required />}{territorial ? <span className="text-xs leading-5 text-zinc-600">Справочник неполный. Проверка: {GUARDIANSHIP_DIRECTORY_METADATA.lastVerifiedAt}.</span> : null}{authority ? <a href={authority.sourceUrl} target="_blank" rel="noreferrer" className="text-xs font-normal text-trust underline">Официальный источник адресата</a> : null}{value === TERRITORY_NOT_FOUND_ID ? <span className="text-xs font-normal text-amber-900">Подтверждённый адресат не найден; материал с адресатом не формируется.</span> : null}</div>;
}
