"use client";
import { LegalReviewLawyers } from "@/components/lawyers/LegalReviewLawyers";
import { useState } from "react";
import Link from "next/link";
import { Download } from "lucide-react";
import { SearchableSelect } from "@/components/forms/SearchableSelect";
import { GUARDIANSHIP_DIRECTORY_METADATA, TERRITORY_NOT_FOUND_ID, findGuardianshipTerritory, getGuardianshipAuthorityOptions, getGuardianshipMunicipalityOptions, getGuardianshipRegionOptions } from "@/data/guardianship-territories";
import { RELATIVE_CHILD_CONTACT_KEYS, RELATIVE_CHILD_CONTACT_SCENARIOS, type RelativeChildContactField, type RelativeChildContactKey } from "@/data/relative-child-contact-route";
import { createRelativeChildContactPdfBlob } from "@/lib/relative-child-contact-pdf";
import { validateRelativeChildContact, type RelativeChildContactDecision, type RelativeChildContactValues } from "@/lib/relative-child-contact-validator";

export function RelativeChildContactHelper({ initialKey }: { initialKey?: RelativeChildContactKey }) {
  const [key, setKey] = useState<RelativeChildContactKey | "">(initialKey ?? ""); const [values, setValues] = useState<RelativeChildContactValues>({}); const [decision, setDecision] = useState<RelativeChildContactDecision | null>(null); const [message, setMessage] = useState("");
  const scenario = key ? RELATIVE_CHILD_CONTACT_SCENARIOS[key] : null;
  function update(name: string, value: string) { setValues((current) => { const next = { ...current, [name]: value }; if (name === "region") { delete next.municipality; delete next.authorityName; } if (name === "municipality") delete next.authorityName; return next; }); setDecision(null); setMessage(""); }
  async function download() { if (!decision?.pdfAvailable) return; try { const blob = await createRelativeChildContactPdfBlob(decision); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `relative-child-contact-${key}.pdf`; anchor.click(); URL.revokeObjectURL(url); setMessage("PDF скачан. Проверьте указанный в нём статус готовности."); } catch { setMessage("Не удалось сформировать PDF. Попробуйте ещё раз."); } }
  return <section id="fill-online" className="scroll-mt-24 border border-line bg-white p-5 shadow-sm sm:p-6"><h2 className="text-2xl font-semibold text-ink">Подготовить материал</h2><p className="mt-2 text-sm leading-6 text-zinc-700">Выберите текущую стадию. Маршрут для родителей находится отдельно.</p>
    <div className="mt-5 grid gap-2"><label htmlFor="relative-contact-scenario" className="text-sm font-semibold text-ink">Что происходит сейчас?</label><select id="relative-contact-scenario" value={key} onChange={(event) => { setKey(event.target.value as RelativeChildContactKey | ""); setValues({}); setDecision(null); }} className="min-h-11 w-full rounded-md border border-line bg-white px-3 py-2 text-base focus:ring-2 focus:ring-trust/30"><option value="">Выберите ситуацию</option>{RELATIVE_CHILD_CONTACT_KEYS.map((item) => <option value={item} key={item}>{RELATIVE_CHILD_CONTACT_SCENARIOS[item].title}</option>)}</select></div>
    {scenario ? <form className="mt-6 grid gap-5" onSubmit={(event) => { event.preventDefault(); setDecision(validateRelativeChildContact(scenario.key, values)); }}>{scenario.questions.map((field) => <Field key={field.name} field={field} values={values} update={update} />)}<button type="submit" className="inline-flex min-h-11 w-fit items-center rounded-md bg-trust px-5 py-3 text-sm font-semibold text-white focus:ring-2 focus:ring-trust/30">Подготовить результат</button></form> : null}
    {decision ? <div className="mt-6 border-t border-line pt-5" aria-live="polite"><h3 className="text-xl font-semibold text-ink">{decision.resultLabel}</h3><p className="mt-2 text-sm font-semibold text-amber-900">Готово к подаче: {decision.filingReady ? "да" : "нет"}. {decision.requiresLegalReview ? "Юридическая проверка обязательна." : "Сверьте реквизиты перед использованием."}</p>{decision.issues.map((issue) => <p key={`${issue.field}-${issue.message}`} className="mt-2 text-sm text-red-800">{issue.message}</p>)}{decision.notices.map((notice) => <p key={notice} className="mt-2 text-sm leading-6 text-zinc-700">{notice}</p>)}
      {decision.outcomeKey === "parent-neighbor-route" ? <Link href="/problems/semya-i-deti/roditeli-i-rebenok-posle-razvoda/" className="mt-4 inline-flex min-h-11 items-center font-semibold text-trust underline">Перейти к маршруту для родителей</Link> : null}
      {decision.outcomeKey === "urgent-child-safety" ? <div className="mt-5 border border-red-300 bg-red-50 p-4 text-sm leading-6 text-red-950"><p className="font-semibold">Немедленное действие</p><p className="mt-2">Если угроза существует сейчас, позвоните <a href="tel:112" className="font-bold underline">112</a>. Не ждите подготовки документа.</p></div> : null}
      {decision.pdfAvailable ? <><h4 className="mt-5 font-semibold text-ink">Что собрать</h4><ul className="mt-2 grid gap-2 text-sm leading-6 text-zinc-700">{decision.evidence.map((item) => <li key={item}>- {item}</li>)}</ul><h4 className="mt-5 font-semibold text-ink">Что делать дальше</h4><ol className="mt-2 grid gap-2 text-sm leading-6 text-zinc-700">{decision.nextSteps.map((item, index) => <li key={item}>{index + 1}. {item}</li>)}</ol><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={download} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-trust px-5 py-3 text-sm font-semibold text-white"><Download className="h-4 w-4" aria-hidden="true" /> Скачать PDF</button><LegalReviewLawyers context={{ route: "/documents/", scenario: String(key), documentTitle: decision.documentTitle }} /></div></> : null}{message ? <p role="status" className="mt-3 text-sm text-zinc-700">{message}</p> : null}</div> : null}
  </section>;
}

function Field({ field, values, update }: { field: RelativeChildContactField; values: RelativeChildContactValues; update: (name: string, value: string) => void }) {
  const id = `relative-contact-${field.name}`; const value = values[field.name] ?? "";
  const territorial = field.type === "territory-region" || field.type === "territory-municipality" || field.type === "guardianship-authority";
  const options = field.type === "territory-region" ? getGuardianshipRegionOptions() : field.type === "territory-municipality" ? getGuardianshipMunicipalityOptions(values.region) : field.type === "guardianship-authority" ? getGuardianshipAuthorityOptions(values.municipality) : [];
  const authority = field.type === "guardianship-authority" ? findGuardianshipTerritory(values.region, values.municipality, value).authority : undefined;
  return <div className="grid gap-2"><label htmlFor={id} className="text-sm font-semibold text-ink">{field.label}</label>{territorial ? <SearchableSelect id={id} label={field.label} options={options} value={value} onChange={(selected) => update(field.name, selected)} required disabled={field.type === "territory-municipality" ? !values.region : field.type === "guardianship-authority" ? !values.municipality || values.municipality === TERRITORY_NOT_FOUND_ID : false} placeholder={field.type === "territory-region" ? "Выберите регион" : field.type === "territory-municipality" ? "Выберите муниципальное образование" : "Выберите орган опеки"} searchPlaceholder={`Поиск: ${field.label.toLowerCase()}`} /> : field.type === "select" ? <select id={id} value={value} onChange={(event) => update(field.name, event.target.value)} className="min-h-11 w-full rounded-md border border-line bg-white px-3 py-2 text-base" required><option value="">Выберите вариант</option>{field.options?.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select> : <textarea id={id} value={value} onChange={(event) => update(field.name, event.target.value)} rows={3} className="min-h-24 w-full rounded-md border border-line bg-white px-3 py-2 text-base" required />}{territorial ? <span className="text-xs leading-5 text-zinc-600">Справочник неполный. Проверка: {GUARDIANSHIP_DIRECTORY_METADATA.lastVerifiedAt}.</span> : null}{authority ? <a href={authority.sourceUrl} target="_blank" rel="noreferrer" className="text-xs font-normal text-trust underline">Официальный источник адресата</a> : null}{value === TERRITORY_NOT_FOUND_ID ? <span className="text-xs font-normal text-amber-900">Подтверждённый адресат не найден; готовый документ не формируется.</span> : null}</div>;
}
